### ISSUE TITLE
Chats to PDF

### ISSUE THREAD

**Issue by shinebarbhuiya** [RblSb/SyncTubeApp#3]
Can you please implement an option to save all the chat of the session to a pdf file? I really want to preserve all those chats we do while watching anything.

**Comment by RblSb** [comment]
On web client, you can login as admin on your server and write /dump command to get current server state with chat history inside. That data can be easily parsed and converted as you want. Also change server message limit (`serverChatHistory`) in user/config.json to bigger value.
I will see if i can add suport to file save dialog to mobile client after.
